# .github/workflows/minikube.yml

name: Minikube CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  minikube-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say hello
        run: echo "Hello, I'm Nithila 👋"

      - name: Setup Minikube
        uses: medyagh/setup-minikube@latest

      - name: Start Minikube
        run: minikube start --driver=docker

      - name: Verify Kubernetes cluster
        run: kubectl cluster-info

      - name: Deploy manifests
        run: kubectl apply -f k8s/

      - name: List Kubernetes resources
        run: kubectl get all
